name: AIclass
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - bioconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  #- appnope
  #- appnope=0.1.0
  - astor=0.7.1
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.6
  - c-ares=1.11.0
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.3.9
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - grpcio=1.12.1
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2019.3
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jasper=2.0.14
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.0.1
  - libcxx
  #- libcxx=4.0.1
  - libcxxabi
  #- libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  #- libgfortran=3.0.1
  - libiconv=1.15
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.36
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libtiff=4.0.10
  - libvpx=1.7.0
  - libxml2=2.9.9
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - mock=3.0.5
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.3
  - notebook=5.7.8
  - numpy=1.16.2
  - numpy-base=1.16.2
  - opencv=3.4.2
  - openssl=1.1.1c
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - pixman=0.38.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - protobuf=3.8.0
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pygments=2.4.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - readline=7.0
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - idisplay==0.1.2
    - py3dmol==0.8.0
prefix: /Users/ykarpievitch/miniconda3/envs/AIclass

