name: AIclass
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - python=3.*
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py37_0
  - appnope=0.1.0=py37_0
  - astor=0.7.1=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.6=h1de35cc_5
  - c-ares=1.11.0=0
  - ca-certificates=2019.5.15=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.3.9=py37_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.2=py37_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - graphite2=1.3.13=h2098e52_0
  - grpcio=1.12.1=py37hd9629dc_0
  - h5py=2.8.0=py37h878fce3_3
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.3=199
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jasper=2.0.14=h636a363_1
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.0.1=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.36=ha441bb4_0
  - libprotobuf=3.8.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.10=hcb84e12_2
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.9=hab757c2_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.0.3=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - mock=3.0.5=py37_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - networkx=2.3=py_0
  - notebook=5.7.8=py37_0
  - numpy=1.16.2=py37hacdab7b_0
  - numpy-base=1.16.2=py37h6575580_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1c=h1de35cc_1
  - pandas=0.24.2=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.0.3=py37_0
  - pixman=0.38.0=h1de35cc_0
  - prometheus_client=0.6.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - protobuf=3.8.0=py37h0a44026_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37h7c891bd_1
  - pygments=2.4.2=py_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.14.11=py37h1de35cc_0
  - python=3.7.3=h359304d_0
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.5.1=py_0
  - readline=7.0=h1de35cc_5
  - scipy=1.2.1=py37h1410ff5_0
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.12.0=py37_0
  - sqlite=3.27.2=ha441bb4_0
  - statsmodels=0.9.0=py37h1d22016_0
  - tensorboard=1.13.1=py37haf313ee_0
  - tensorflow=1.13.1=mkl_py37h70c3834_0
  - tensorflow-base=1.13.1=mkl_py37h66b1bf0_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.2=py37h1de35cc_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.1=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - idisplay==0.1.2
    - py3dmol==0.8.0
